version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: "12.0.0"
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    steps:
      - checkout
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan
          
workflows:
  version: 2.1
  build-test-adhoc:
    jobs:
      - build-and-test
      - beta:
          filters:
            branches:
              only: master
          requires:
            - build-and-test
